apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.30.0 (HEAD)
  labels:
    io.kompose.service: csvs-webserver
  name: csvs-webserver
  namespace: csvs
spec:
  type: NodePort                         
  selector:
    io.kompose.service: csvs-webserver   
  ports:
    - name: "80"
      protocol: TCP
      port: 80                           
      targetPort: 80                    
      nodePort: 30080                   
status:
  loadBalancer: {}
